version: "3.8"

services:
  github-ingestor:
    build: .
    env_file: .env
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
